apiVersion: v1
data:
  ingressName: envoy-ingress
  istioNamespace: istio-system
  oauthSecretName: kubeflow-oauth
  appName: kubeflow-test # {"$kpt-set":"name-label"}
  hostname: kubeflow-test.endpoints.gcp-dev-ops.cloud.goog # {"$kpt-set":"hostname"}
  ipName: kubeflow-test-ip # {"$kpt-set":"ip-name"}
  project: "gcp-dev-ops" # {"$kpt-set":"gcloud.core.project"}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: iap-ingress-config
