apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-pipeline-ui
  annotations:
    iam.gke.io/gcp-service-account: kubeflow-test-user@gcp-dev-ops.iam.gserviceaccount.com # {"$kpt-set":"user-sa-ref"}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-pipeline-visualizationserver
  annotations:
    iam.gke.io/gcp-service-account: kubeflow-test-user@gcp-dev-ops.iam.gserviceaccount.com # {"$kpt-set":"user-sa-ref"}
