apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cnrm-system-gcp-dev-ops-owner # {"$kpt-set":"managed-project-policy-name"}
  namespace: gcp-dev-ops # {"$kpt-set":"managed-project"}
spec:
  member: serviceAccount:kubemgmt-cnrm-system@gcp-dev-ops.iam.gserviceaccount.com # {"$kpt-set":"managed-project-owner-member"}
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    # N.B. With anthoscli 0.2.4 this is just the project id
    # and not projects/MANAGED_PROJECT as used by the CNRM docs.
    external: gcp-dev-ops # {"$kpt-set":"managed-project"}
